import { useMemo } from 'react';
import { Dimensions, StyleSheet } from 'react-native';
import { useThemedScreen } from '../../../hooks/useThemedScreen';
import { colors as palette } from '../../../constants/colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export function useEmployeeScheduleStyles() {
  const { screen, ui, theme } = useThemedScreen();

  return useMemo(() => {
    const segmentBg = theme === 'dark' ? '#2A2A2A' : '#ECECEC';
    const mutedSurface = theme === 'dark' ? '#252525' : '#FAFAFA';

    return StyleSheet.create({
      header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 12,
        paddingBottom: 14,
        paddingHorizontal: 12,
      },
      headerSide: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
      headerCenter: { flex: 1, alignItems: 'center' },
      headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFFFFF' },
      headerSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },

      summaryCard: {
        marginHorizontal: 16,
        marginTop: 16,
        backgroundColor: screen.card,
        borderRadius: 14,
        padding: 14,
        borderWidth: 1,
        borderColor: screen.border,
      },
      summaryText: { fontSize: 14, color: screen.textSecondary, textAlign: 'center' },
      summaryHighlight: { fontWeight: '700', color: palette.primary },

      calendarToggle: {
        flexDirection: 'row',
        marginHorizontal: 16,
        marginTop: 12,
        backgroundColor: segmentBg,
        borderRadius: 12,
        padding: 4,
      },
      calToggleBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' },
      calToggleBtnActive: { backgroundColor: screen.card },
      calToggleText: { fontSize: 13, color: screen.textSecondary, fontWeight: '500' },
      calToggleTextActive: { color: palette.primary, fontWeight: '600' },

      periodNavigation: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
      },
      navButton: { padding: 8 },
      periodTitleWrap: { flex: 1, alignItems: 'center' },
      periodTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: screen.text,
        textTransform: 'capitalize',
      },
      todayHint: { fontSize: 11, color: palette.primary, marginTop: 2 },

      viewToggle: {
        flexDirection: 'row',
        marginHorizontal: 16,
        marginBottom: 10,
        backgroundColor: segmentBg,
        borderRadius: 12,
        padding: 4,
      },
      toggleBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' },
      toggleBtnActive: { backgroundColor: screen.card },
      toggleText: { fontSize: 13, color: screen.textSecondary, fontWeight: '500' },
      toggleTextActive: { color: palette.primary, fontWeight: '600' },

      teamFilter: { paddingHorizontal: 16, marginBottom: 10 },
      filterChip: {
        paddingHorizontal: 14,
        paddingVertical: 7,
        borderRadius: 16,
        backgroundColor: ui.input.backgroundColor,
        marginRight: 8,
      },
      filterChipActive: { backgroundColor: palette.primary },
      filterChipText: { fontSize: 13, color: screen.textSecondary },
      filterChipTextActive: { color: '#FFFFFF' },

      gridCard: {
        marginHorizontal: 16,
        backgroundColor: screen.card,
        borderRadius: 16,
        paddingVertical: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: screen.border,
      },

      weekGridScroll: { paddingHorizontal: 8 },
      weekGrid: { flexDirection: 'row', gap: 4 },
      weekColumn: { alignItems: 'stretch' },
      weekColumnHeader: {
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 4,
        borderRadius: 12,
        backgroundColor: ui.input.backgroundColor,
        borderWidth: 1,
        borderColor: screen.border,
        minHeight: 64,
      },
      weekColumnHeaderToday: { borderColor: palette.primary },
      weekColumnHeaderSelected: { backgroundColor: palette.primary, borderColor: palette.primary },
      weekColumnWeekday: { fontSize: 10, color: screen.textSecondary, fontWeight: '600' },
      weekColumnDate: { fontSize: 18, fontWeight: '700', color: screen.text, marginTop: 2 },
      weekColumnHeaderTextActive: { color: '#FFFFFF' },
      weekBadge: {
        marginTop: 4,
        backgroundColor: palette.primaryLight,
        borderRadius: 8,
        paddingHorizontal: 6,
        paddingVertical: 1,
      },
      weekBadgeSelected: { backgroundColor: 'rgba(255,255,255,0.25)' },
      weekBadgeText: { fontSize: 10, fontWeight: '700', color: palette.primary },
      weekBadgeTextSelected: { color: '#FFFFFF' },
      weekColumnBody: {
        marginTop: 6,
        minHeight: 88,
        padding: 4,
        borderRadius: 10,
        backgroundColor: mutedSurface,
        gap: 4,
      },
      weekColumnBodySelected: {
        backgroundColor: palette.primaryLight,
        borderWidth: 1,
        borderColor: 'rgba(108,92,231,0.2)',
      },
      weekEmpty: { fontSize: 14, color: screen.textSecondary, textAlign: 'center', marginTop: 24 },

      shiftPill: {
        borderRadius: 8,
        paddingHorizontal: 6,
        paddingVertical: 5,
        alignItems: 'center',
      },
      shiftPillCompact: { paddingVertical: 4 },
      shiftPillMine: { backgroundColor: palette.primary },
      shiftPillOther: {
        backgroundColor: screen.card,
        borderWidth: 1,
        borderColor: screen.border,
      },
      shiftPillTime: { fontSize: 10, fontWeight: '700', color: screen.text },
      shiftPillTextLight: { color: '#FFFFFF' },
      shiftPillName: { fontSize: 9, color: screen.textSecondary, marginTop: 1 },
      shiftPillSwapIcon: { marginTop: 2 },

      monthSection: { paddingHorizontal: 8 },
      monthWeekdays: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 6,
      },
      monthWeekday: {
        width: '14.28%',
        textAlign: 'center',
        fontSize: 11,
        color: screen.textSecondary,
        fontWeight: '600',
      },
      monthGrid: { flexDirection: 'row', flexWrap: 'wrap' },
      monthCell: {
        width: '14.28%',
        aspectRatio: 1,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        padding: 2,
      },
      monthCellOutside: { opacity: 0.35 },
      monthCellToday: { borderWidth: 1.5, borderColor: palette.primary },
      monthCellSelected: { backgroundColor: palette.primary },
      monthCellWithShift: { backgroundColor: palette.primaryLight },
      monthCellDate: { fontSize: 13, fontWeight: '600', color: screen.text },
      monthCellDateOutside: { color: screen.textSecondary },
      monthCellDateActive: { color: '#FFFFFF', fontWeight: '700' },
      monthDots: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        marginTop: 2,
        flexWrap: 'wrap',
        justifyContent: 'center',
      },
      monthDot: { width: 5, height: 5, borderRadius: 3 },
      monthDotMine: { backgroundColor: palette.primary },
      monthDotOther: { backgroundColor: '#B0BEC5' },
      monthDotMore: { fontSize: 8, color: screen.textSecondary, fontWeight: '600' },

      legend: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 16,
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: screen.border,
        marginHorizontal: 12,
      },
      legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
      legendDot: { width: 8, height: 8, borderRadius: 4 },
      legendDotMine: { backgroundColor: palette.primary },
      legendDotOther: { backgroundColor: '#B0BEC5' },
      legendText: { fontSize: 11, color: screen.textSecondary },

      dayDetailSection: { paddingHorizontal: 16, marginBottom: 8 },
      dayDetailHeader: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 8,
        marginBottom: 10,
      },
      dayDetailTitle: { fontSize: 16, fontWeight: '700', color: screen.text },
      dayDetailSub: { fontSize: 12, color: screen.textSecondary },

      emptyDay: {
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: screen.card,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: screen.border,
        alignItems: 'center',
      },
      emptyDayText: { fontSize: 14, color: screen.textSecondary },
      emptyDayBtn: {
        marginTop: 10,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: palette.primaryLight,
      },
      emptyDayBtnText: { fontSize: 13, color: palette.primary, fontWeight: '600' },

      dayDetailGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
      },
      detailCard: {
        width: (SCREEN_WIDTH - 32 - 10) / 2,
        backgroundColor: screen.card,
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
        borderColor: screen.border,
      },
      detailCardMine: { backgroundColor: palette.primary, borderColor: palette.primary },
      detailTime: { fontSize: 15, fontWeight: '700', color: screen.text },
      detailName: { fontSize: 13, color: screen.textSecondary, marginTop: 4 },
      detailType: { fontSize: 11, color: screen.textSecondary, marginTop: 2 },
      detailTextLight: { color: '#FFFFFF' },
      detailTextMuted: { color: 'rgba(255,255,255,0.75)' },
      detailSwapRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8 },
      detailSwapText: { fontSize: 11, color: '#FFFFFF', fontWeight: '500' },

      requestsLink: { marginHorizontal: 16, marginTop: 4, padding: 14, alignItems: 'center' },
      requestsLinkText: { fontSize: 14, color: palette.primary, fontWeight: '500' },

      bottomSpacer: { height: 24 },

      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContent: {
        backgroundColor: screen.card,
        borderRadius: 24,
        width: '90%',
        maxHeight: '85%',
        padding: 20,
      },
      modalTitle: { fontSize: 20, fontWeight: 'bold', color: screen.text, marginBottom: 16 },
      selectedShiftInfo: {
        backgroundColor: ui.input.backgroundColor,
        borderRadius: 12,
        padding: 12,
        marginBottom: 8,
      },
      shiftInfoLabel: { fontSize: 12, color: screen.textSecondary, marginBottom: 4 },
      shiftInfoText: { fontSize: 14, color: screen.text, fontWeight: '500' },
      inputLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: screen.text,
        marginBottom: 8,
        marginTop: 12,
      },
      noShiftsHint: { fontSize: 13, color: screen.textSecondary, marginBottom: 8 },
      employeeSelectList: { maxHeight: 180 },
      employeeSelectItem: {
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 10,
        marginBottom: 6,
        backgroundColor: ui.input.backgroundColor,
      },
      employeeSelectItemActive: { backgroundColor: palette.primary },
      employeeSelectText: { fontSize: 15, color: screen.text },
      employeeSelectTextActive: { color: '#FFFFFF' },
      reasonInput: {
        backgroundColor: ui.input.backgroundColor,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 14,
        minHeight: 56,
        textAlignVertical: 'top',
        color: screen.text,
      },
      submitButton: { marginTop: 20, borderRadius: 30, overflow: 'hidden' },
      submitGradient: { paddingVertical: 14, alignItems: 'center' },
      submitButtonText: { fontSize: 16, fontWeight: '600', color: '#FFFFFF' },
      cancelButton: { marginTop: 12, alignItems: 'center', padding: 8 },
      cancelButtonText: { fontSize: 14, color: screen.textSecondary },
    });
  }, [screen, ui, theme]);
}
