import { Dimensions, Platform, StyleSheet } from 'react-native';
import { colors } from '../../../constants/colors';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const scheduleStyles = StyleSheet.create({
  container: { flex: 1 },

  pvzSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 16,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  pvzSelectorLabel: { fontSize: 13 },
  pvzSelectorValue: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pvzSelectorText: { fontSize: 13, fontWeight: '500', color: colors.primary },

  pvzDropdown: {
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  pvzDropdownItem: { padding: 12, borderBottomWidth: 1 },
  pvzDropdownItemActive: { backgroundColor: colors.primaryLight },
  pvzDropdownText: { fontSize: 14 },
  pvzDropdownTextActive: { color: colors.primary, fontWeight: '500' },

  controlPanel: { padding: 16, borderBottomWidth: 1 },
  viewModeSelector: { flexDirection: 'row', borderRadius: 12, marginBottom: 12 },
  viewModeButton: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 12 },
  viewModeActive: { backgroundColor: colors.primary },
  viewModeText: { fontSize: 14 },
  viewModeTextActive: { color: '#FFFFFF', fontWeight: '500' },

  navigationRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  navButton: { padding: 8 },
  dateRangeText: { fontSize: 14, fontWeight: '500' },

  gridContainer: { padding: 8 },
  gridHeader: { flexDirection: 'row', borderBottomWidth: 1, paddingBottom: 8, marginBottom: 8 },
  gridRow: { flexDirection: 'row', marginBottom: 4, minHeight: 70 },
  gridCell: { width: 80, justifyContent: 'center', alignItems: 'center', padding: 4 },
  employeeHeaderCell: { width: 120, alignItems: 'flex-start' },
  employeeHeaderText: { fontSize: 12, fontWeight: '600' },
  dateHeaderCell: { width: 80 },
  weekdayText: { fontSize: 11, fontWeight: '500' },
  dateText: { fontSize: 10, marginTop: 2 },

  employeeCell: { width: 120, alignItems: 'flex-start' },
  employeeName: { fontSize: 13, fontWeight: '500' },
  employeeRole: { fontSize: 10, marginTop: 2 },

  shiftCell: { width: 80, borderRadius: 8, marginHorizontal: 2, justifyContent: 'center', minHeight: 70 },
  shiftContent: { alignItems: 'center' },
  shiftBadge: { paddingHorizontal: 6, paddingVertical: 4, borderRadius: 8, alignItems: 'center' },
  shiftBadgeText: { fontSize: 10, color: '#FFFFFF', fontWeight: '500', textAlign: 'center' },
  shiftTimeText: { fontSize: 8, color: '#FFFFFF', marginTop: 2, textAlign: 'center' },
  paymentStatusBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, marginTop: 4 },
  paymentStatusText: { fontSize: 9, fontWeight: '500' },
  shiftEarnings: { fontSize: 9, color: colors.success, marginTop: 2, fontWeight: '500' },
  addShiftPlaceholder: { alignItems: 'center', justifyContent: 'center' },

  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)' },
  keyboardAvoidingView: { width: '100%', alignItems: 'center', zIndex: 1 },
  modalContent: {
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxHeight: SCREEN_HEIGHT * 0.85,
    overflow: 'hidden',
  },
  modalScrollView: {
    maxHeight: SCREEN_HEIGHT * 0.52,
    flexGrow: 0,
    flexShrink: 1,
  },
  modalScrollContent: { paddingBottom: 16 },
  modalFooter: {
    flexShrink: 0,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 8, textAlign: 'center' },

  selectedEmployeeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 12,
    alignSelf: 'center',
  },
  selectedEmployeeText: { fontSize: 13, color: colors.primary },
  selectedEmployeeName: { fontWeight: 'bold', color: colors.primary },

  modalSubtitle: { fontSize: 14, color: colors.gray, textAlign: 'center', marginBottom: 20 },

  shiftTypesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20 },
  shiftTypeCard: { flex: 1, minWidth: '45%', padding: 12, borderRadius: 12, borderWidth: 1, alignItems: 'center' },
  shiftTypeCardActive: { borderWidth: 2, backgroundColor: '#F5F5F5' },
  shiftTypeColor: { width: 24, height: 24, borderRadius: 12, marginBottom: 6 },
  shiftTypeName: { fontSize: 12, fontWeight: '500', textAlign: 'center' },
  shiftTypeTime: { fontSize: 10, marginTop: 2 },

  customTimeContainer: { marginBottom: 20 },
  customTimeLabel: { fontSize: 14, fontWeight: '500', marginBottom: 12 },
  hourlyTimeRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  hourlyTimeField: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  hourlyTimeFieldError: { borderColor: colors.danger },
  hourlyTimeCaption: { fontSize: 11, color: '#999', marginBottom: 4 },
  hourlyTimePickerRow: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  hourlyTimeDisplay: {
    fontSize: 22,
    fontWeight: '600',
    textAlign: 'center',
  },
  hourlyTimeDivider: { fontSize: 18, color: '#999', paddingBottom: 20 },
  hourlyDuration: { fontSize: 13, color: colors.primary, marginTop: 10, textAlign: 'center', fontWeight: '500' },
  errorText: { fontSize: 12, color: colors.danger, marginTop: 6, textAlign: 'center' },

  fullScreenPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 100,
  },
  inlinePickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  pickerSheet: {
    width: '100%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 28 : 16,
    paddingHorizontal: 20,
    zIndex: 101,
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  pickerSpinnerContainer: {
    width: '100%',
    height: 216,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  pickerSpinner: {
    width: '100%',
    height: 216,
  },
  pickerActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 12,
  },
  pickerCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
  },
  pickerCancelText: { fontSize: 16, color: '#666', fontWeight: '500' },
  pickerDoneButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  pickerDoneText: { fontSize: 16, color: '#FFFFFF', fontWeight: '600' },

  earningsPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#E8F5E9',
    borderRadius: 12,
    padding: 12,
    marginBottom: 4,
  },
  earningsPreviewText: { fontSize: 14 },
  earningsPreviewValue: { fontSize: 18, fontWeight: 'bold', color: colors.success },

  modalButtons: { flexDirection: 'row', gap: 12 },
  cancelButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  cancelButtonText: { fontSize: 16, color: '#666', fontWeight: '500' },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  saveButtonText: { fontSize: 16, color: '#FFFFFF', fontWeight: '500' },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#FFEBEE',
    marginTop: 10,
  },
  deleteButtonText: { fontSize: 16, color: colors.danger, fontWeight: '500' },

  modalInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 16,
  },
  inputLabel: { fontSize: 14, fontWeight: '500', marginBottom: 8 },

  quickActionsBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    gap: 16,
  },
  quickAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  quickActionText: { fontSize: 12, color: colors.primary, fontWeight: '500' },
});
