import { User, Pvz, defaultPermissions } from '../../types/user';

export const DEMO_PVZ: Pvz[] = [
  {
    id: 'pvz1',
    name: 'ПВЗ на Спортивной',
    address: 'ул. Спортивная, д. 10',
    workingHours: '10:00 - 21:00',
    workStart: '10:00',
    workEnd: '21:00',
    phone: '+7 (999) 111-22-33',
    ownerId: '1',
  },
  {
    id: 'pvz2',
    name: 'ПВЗ на Ленина',
    address: 'ул. Ленина, д. 25',
    workingHours: '09:00 - 20:00',
    workStart: '09:00',
    workEnd: '20:00',
    phone: '+7 (999) 222-33-44',
    ownerId: '1',
  },
];

export const DEMO_USERS: User[] = [
  {
    id: '1',
    name: 'Анатолий',
    email: 'owner@pvz.ru',
    phone: '79991234567',
    role: 'owner',
    status: 'active',
    createdAt: new Date().toISOString(),
    passwordHash: '',
  },
  {
    id: '2',
    name: 'Мария',
    email: 'admin@pvz.ru',
    phone: '79992345678',
    role: 'admin',
    status: 'active',
    pvzId: 'pvz1',
    pvzIds: ['pvz1', 'pvz2'],
    permissionLevel: 'full',
    createdAt: new Date().toISOString(),
    passwordHash: '',
  },
  {
    id: '3',
    name: 'Леонид',
    email: 'emp@pvz.ru',
    phone: '79143288207',
    role: 'employee',
    status: 'active',
    pvzId: 'pvz1',
    createdAt: new Date().toISOString(),
    permissions: { ...defaultPermissions },
    passwordHash: '',
  },
  {
    id: '4',
    name: 'Илья',
    email: 'ilya@pvz.ru',
    phone: '79995678901',
    role: 'employee',
    status: 'active',
    pvzId: 'pvz1',
    createdAt: new Date().toISOString(),
    permissions: { ...defaultPermissions },
    passwordHash: '',
  },
  {
    id: '5',
    name: 'Саша',
    email: 'sasha@pvz.ru',
    phone: '79996789012',
    role: 'employee',
    status: 'active',
    pvzId: 'pvz1',
    createdAt: new Date().toISOString(),
    permissions: { ...defaultPermissions },
    passwordHash: '',
  },
];
